wandb_version: 1

model:
  desc: null
  value: facebook/bart-large-cnn
lora_r:
  desc: null
  value: 16
lora_alpha:
  desc: null
  value: 32
lora_dropout:
  desc: null
  value: 0.05
batch_size:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 5.0e-05
weight_decay:
  desc: null
  value: 0.01
num_epochs:
  desc: null
  value: 1
max_input_length:
  desc: null
  value: 512
max_target_length:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    python_version: 3.10.5
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1747211081.891671
    t:
      1:
      - 1
      - 5
      - 11
      - 40
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 13
      - 16
      - 23
      4: 3.10.5
      5: 0.16.2
      6: 4.37.2
      8:
      - 5
      13: darwin-arm64
